---
# tasks file for roles/launch-database
- name: Run Database
  docker_container:
    name: devops-database-1
    image: matmed/tp01-database:1.1
    env:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    networks:
      - name: my-network