---
# tasks file for roles/create-network
- name: Create a network
  community.docker.docker_network:
    name: my-network
    state: present

#- name: Remove all but selected list of containers
#  community.docker.docker_network:
#    name: my-network
#    connected:
#      - httpd
#      - database
#      - backend

#- name: Add a container to a network, leaving existing containers connected
#  community.docker.docker_network:
#    name: my-network
#    connected:
#      - httpd
#      - database
#      - backend
#    appends: true
