---
# tasks file for roles/launch-proxy
- name: Run HTTPD
  docker_container:
    name: devops-httpd-1
    image: matmed/tp01-httpd:1.1
    networks:
      - name: my-network
    ports:
      - "80:80"
